export type Word = {
  id: string
  word: string
  phonetic: string
  pos: string
  meaning: string
  meaningExtra: string
  example: string
  exampleKo: string
  mnemonic: string
  image: string
}

export const WORDS: Word[] = [
  {
    id: 'abandon',
    word: 'abandon',
    phonetic: '/əˈbæn.dən/',
    pos: '동사',
    meaning: '버리다, 포기하다',
    meaningExtra: '사람·장소·계획을 완전히 떠나거나 그만두다',
    example: 'They had to abandon the boat and swim to shore.',
    exampleKo: '그들은 배를 버리고 해안까지 헤엄쳐야 했다.',
    mnemonic: '"어! 밴드(band)가 없어" — 밴드가 무대를 버리고 떠난 장면을 떠올리세요.',
    image: '/words/abandon.png',
  },
  {
    id: 'brilliant',
    word: 'brilliant',
    phonetic: '/ˈbrɪl.jənt/',
    pos: '형용사',
    meaning: '눈부신, 훌륭한',
    meaningExtra: '빛이 아주 밝거나, 재능이 뛰어난',
    example: 'She came up with a brilliant solution in ten seconds.',
    exampleKo: '그녀는 10초 만에 훌륭한 해법을 떠올렸다.',
    mnemonic: '브릴리언트 컷 다이아몬드 — 빛이 사방으로 터지는 이미지와 함께 기억하세요.',
    image: '/words/brilliant.png',
  },
  {
    id: 'curious',
    word: 'curious',
    phonetic: '/ˈkjʊər.i.əs/',
    pos: '형용사',
    meaning: '호기심 많은',
    meaningExtra: '알고 싶어 하는, 때로는 기이한',
    example: 'The curious cat opened the glowing box.',
    exampleKo: '호기심 많은 고양이가 빛나는 상자를 열었다.',
    mnemonic: '"큐리어스" 고양이 꼬리가 물음표(?) 모양이라고 상상하세요.',
    image: '/words/curious.png',
  },
  {
    id: 'dedicate',
    word: 'dedicate',
    phonetic: '/ˈded.ɪ.keɪt/',
    pos: '동사',
    meaning: '헌신하다, 바치다',
    meaningExtra: '시간·노력을 어떤 목적에 온전히 쓰다',
    example: 'He dedicated ten years to studying memory.',
    exampleKo: '그는 기억 연구에 10년을 바쳤다.',
    mnemonic: '새벽 트랙 위의 닳은 러닝화 — 바친 시간이 신발에 남습니다.',
    image: '/words/dedicate.png',
  },
  {
    id: 'eager',
    word: 'eager',
    phonetic: '/ˈiː.ɡɚ/',
    pos: '형용사',
    meaning: '열망하는, 몹시 하고 싶은',
    meaningExtra: '기대감으로 몸이 앞으로 기울 정도의 상태',
    example: 'The students were eager to start the quiz.',
    exampleKo: '학생들은 퀴즈를 시작하고 싶어 안달이 났다.',
    mnemonic: '목줄을 앞으로 끌어당기는 강아지 — 몸이 먼저 나갑니다.',
    image: '/words/eager.png',
  },
  {
    id: 'fragile',
    word: 'fragile',
    phonetic: '/ˈfrædʒ.aɪl/',
    pos: '형용사',
    meaning: '부서지기 쉬운, 연약한',
    meaningExtra: '쉽게 깨지거나 손상되는',
    example: 'Handle this fragile glass egg with both hands.',
    exampleKo: '이 깨지기 쉬운 유리 달걀은 두 손으로 다뤄라.',
    mnemonic: '택배 상자의 FRAGILE 스티커 — 유리 달걀에 금이 가는 순간.',
    image: '/words/fragile.png',
  },
  {
    id: 'generous',
    word: 'generous',
    phonetic: '/ˈdʒen.ər.əs/',
    pos: '형용사',
    meaning: '관대한, 후한',
    meaningExtra: '자기 것을 아끼지 않고 잘 나눠 주는',
    example: 'A generous donor paid for the whole library.',
    exampleKo: '한 관대한 후원자가 도서관 전체 비용을 냈다.',
    mnemonic: '넘칠 만큼 쏟아 붓는 두 손 — 손이 크면 generous.',
    image: '/words/generous.png',
  },
  {
    id: 'horizon',
    word: 'horizon',
    phonetic: '/həˈraɪ.zən/',
    pos: '명사',
    meaning: '수평선, 지평선',
    meaningExtra: '하늘과 땅(바다)이 만나는 선, 시야의 한계',
    example: 'A single sail appeared on the horizon.',
    exampleKo: '수평선 위에 돛 하나가 나타났다.',
    mnemonic: '"호라이즌"의 rise — 해가 그 선에서 떠오릅니다.',
    image: '/words/horizon.png',
  },
  {
    id: 'inevitable',
    word: 'inevitable',
    phonetic: '/ɪˈnev.ə.t̬ə.bəl/',
    pos: '형용사',
    meaning: '피할 수 없는, 필연적인',
    meaningExtra: '반드시 일어나게 되어 있는',
    example: 'Forgetting is inevitable without review.',
    exampleKo: '복습이 없으면 망각은 피할 수 없다.',
    mnemonic: '첫 도미노가 기울면 나머지는 정해진 결말.',
    image: '/words/inevitable.png',
  },
  {
    id: 'jealous',
    word: 'jealous',
    phonetic: '/ˈdʒel.əs/',
    pos: '형용사',
    meaning: '질투하는, 시샘하는',
    meaningExtra: '남이 가진 것을 부러워하며 불편해하는',
    example: 'He was jealous of her trophy.',
    exampleKo: '그는 그녀의 트로피를 질투했다.',
    mnemonic: '창밖에서 트로피를 바라보는 그림자 — 초록빛 눈.',
    image: '/words/jealous.png',
  },
  {
    id: 'luminous',
    word: 'luminous',
    phonetic: '/ˈluː.mə.nəs/',
    pos: '형용사',
    meaning: '빛나는, 발광하는',
    meaningExtra: '스스로 빛을 내어 어둠에서도 보이는',
    example: 'Luminous fireflies lit the forest path.',
    exampleKo: '빛나는 반딧불이들이 숲길을 비췄다.',
    mnemonic: 'lumen(루멘, 빛의 단위) + ous — 반딧불이 병.',
    image: '/words/luminous.png',
  },
  {
    id: 'modest',
    word: 'modest',
    phonetic: '/ˈmɑː.dɪst/',
    pos: '형용사',
    meaning: '겸손한, 그리 크지 않은',
    meaningExtra: '자기 능력을 과시하지 않는, 규모가 적당한',
    example: 'Despite winning, she stayed modest.',
    exampleKo: '우승했음에도 그녀는 겸손했다.',
    mnemonic: '시상대에서 내려와 메달을 건네는 챔피언.',
    image: '/words/modest.png',
  },
]

export const WORD_MAP: Record<string, Word> = Object.fromEntries(WORDS.map((w) => [w.id, w]))
